---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mystorea/public_html
    - >
      /bin/rsync -rlt --delete
      --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r
      --exclude='.env'
      --exclude='/vendor'
      --exclude='/node_modules'
      --exclude='/mobile'
      --exclude='/storage/logs'
      --exclude='/storage/uploads'
      --exclude='/storage/framework'
      --exclude='/storage/installed'
      --exclude='/storage/*.key'
      --exclude='/storage/pail'
      --exclude='/public/storage'
      --exclude='/public/hot'
      --exclude='/bootstrap/ssr'
      --exclude='/bootstrap/cache'
      --exclude='/auth.json'
      --exclude='/.git'
      ./ $DEPLOYPATH/
    - /bin/chmod 755 $DEPLOYPATH
