---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mystorea/public_html
    - >
      /bin/rsync -a --delete
      --exclude='.env'
      --exclude='/vendor'
      --exclude='/node_modules'
      --exclude='/mobile'
      --exclude='/storage/logs'
      --exclude='/storage/uploads'
      --exclude='/storage/framework'
      --exclude='/.git'
      ./ $DEPLOYPATH/
